---

- name: Ensure PostgreSQL is installed at the latest version
  apt: name={{item}} state=latest
  with_items:
    - postgresql
    - postgresql-client
    - postgresql-contrib

- name: Ensure PostgreSQL dependencies are installed at the latest version
  apt: name={{item}} state=latest
  with_items:
    - libpq-dev
    - python-psycopg2
    - python-pycurl
    - locales

- name: Add mangaki database in PostgreSQL
  postgresql_db: name={{mangaki_db_name}} encoding='UTF-8' lc_collate='fr_FR.UTF-8' lc_ctype='fr_FR.UTF-8' template='template0'
  become: yes
  become_user: postgres
- name: Add mangaki user in PostgreSQL
  postgresql_user: db={{mangaki_db_name}} name={{mangaki_db_user}} password={{mangaki_db_password | mandatory}} priv=ALL state=present
  become: yes
  become_user: postgres
